version: "3.9"
services:
  nginx:
    ports:
      - "3000:80"
      
  node-app:
    build:
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app
      # - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=honey
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=myredissecret
      
  
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=honey
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
